routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::resource('users', 'Admin\UsersController');
    Route::resource('faculties', 'Admin\FacultiesController');
});

Route::group(['prefix' => 'profile', 'middleware' => 'auth'], function () {
    //Route::resource('faculties', 'Users\ProfilesController');
});

Route::get('/home', 'HomeController@index');

app/Faculty.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Faculty extends Model
{
    /**
     * @var array
     */
    protected $fillable = [
        'faculty',
        'created_at',
    ];

    public $timestamps = false;

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function profile()
    {
        return $this->hasOne('App\Profile');
    }
}

app/Http/Controllers/Admin/FacultiesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Faculty;
use App\Http\Controllers\MainController;
use App\Http\Requests\FacultiesPostRequest;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FacultiesController extends MainController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->data['title'] = 'Faculties page';
        $this->data['panel_title'] = 'Faculties items';
        $this->data['faculties'] = Faculty::paginate(50);
        return view('admin.pages.faculties.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->data['title'] = 'Create faculty';
        $this->data['panel_title'] = 'Form create faculty';
        return view('admin.pages.faculties.create', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FacultiesPostRequest $request)
    {
        $faculty = new Faculty();
        $faculty->faculty = $request->name;
        $faculty->created_at = Carbon::now();
        $faculty->save();

        return redirect()->route('faculties.index')->with('success', 'Faculty create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function show($id)
    {
        return abort(404);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->data['title'] = 'Edit faculty';
        $this->data['panel_title'] = 'Form edit faculty';
        $this->data['faculty'] = Faculty::find($id);

        return view('admin.pages.faculties.edit', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(FacultiesPostRequest $request, $id)
    {
        $faculty = Faculty::findOrFail($id);
        $faculty->faculty = $request->name;

        $faculty->save();
        return redirect()->route('faculties.index')->with('success', 'Faculty update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $faculty = Faculty::findOrFail($id);
        $faculty->delete();
        return redirect()->route('faculties.index')->with('success', 'Faculty delete');
    }
}

resources/views/admin/pages/faculties/create.blade.php
@extends('admin.app')

@section('content')
    <form action="{{ route('faculties.store') }}" method="post" enctype="multipart/form-data">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group input-group">
                    <span class="input-group-addon">Faculty name</span>
                    <input type="text" class="form-control" required placeholder="Faculty name" name="name">
                </div>
            </div>

        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
@endsection

resources/views/admin/pages/faculties/edit.blade.php
@extends('admin.app')

@section('content')
    <form action="{{ route('faculties.update', $faculty->id) }}" method="post" enctype="multipart/form-data">
        <input type="hidden" name="_method" value="PUT">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group input-group">
                    <span class="input-group-addon">Faculty name</span>
                    <input type="text" class="form-control" required placeholder="Faculty name" name="name" value="{{ $faculty->faculty }}">
                </div>
            </div>

        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
@endsection

resources/views/admin/pages/faculties/index.blade.php
@extends('admin.app')

@push('styles')
<!-- DataTables CSS -->
<link href="../vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">
<!-- DataTables Responsive CSS -->
<link href="../vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">
@endpush

@section('content')
    <div class="row">
        <div class="col-md-6">
            <a href="{{ route('faculties.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i></a>
        </div>
    </div>
    @if(count($faculties) > 0)
    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead>
        <tr>
            <th>#</th>
            <th>Faculty name</th>
            <th>Created</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach($faculties as $key => $faculty)
        <tr class="@if($key % 2) odd @else even @endif gradeX">
            <td>{{ $key + 1 }}</td>
            <td>{{ $faculty->faculty }}</td>
            <td>{{ $faculty->created_at }}</td>
            <td class="center">
                <a href="{{ route('faculties.edit', $faculty->id) }}" class="btn btn-primary btn-circle"><i class="fa fa-pencil"></i></a>
            </td>
            <td class="center">
                <form action="{{ route('faculties.destroy', $faculty->id) }}" method="POST" onsubmit="return confirm('Delete?')">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <button class="btn btn-warning btn-circle"><i class="fa fa-times"></i></button>
                </form>
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>
    <!-- /.table-responsive -->
    @endif
@endsection

@push('scripts')
<!-- DataTables JavaScript -->
<script src="/sb-admin-2/vendor/datatables/js/jquery.dataTables.min.js"></script>
<script src="/sb-admin-2/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
<script src="/sb-admin-2/vendor/datatables-responsive/dataTables.responsive.js"></script>

<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
            responsive: true
        });
    });
</script>
@endpush